language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
install: true
sudo: required
cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean install
  - bash <(curl -s https://codecov.io/bash)
